# AUTO-GENERATED by ctfd/main.tf — 請勿手動修改
# 每次 tofu apply（ctfd 層）後自動更新
# 如需修改靜態設定（flag、flavor 等），請編輯 group_vars/all/challenge.yml

# ctfd tofu output → network_id
challenge_network_id: "${network_id}"

# platform tofu output → image_ids.ubuntu2204（由 ctfd 層的 var.image_id 傳入）
challenge_image_id: "${image_id}"
